apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animals-inference
  template:
    metadata:
      labels:
        app: animals-inference
    spec:
      containers:
      - name: animals-inference
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 5000
